[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Form redirects
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

[[redirects]]
  from = "/estimate-success"  
  to = "/estimate-success.html"
  status = 200

# Catch-all redirect for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
