[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Static file serving for success pages
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200
  force = false

[[redirects]]
  from = "/estimate-success"  
  to = "/estimate-success.html"
  status = 200
  force = false
